[package]
name = "rasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.23" }
[dependencies.fallthrough]
git = "https://github.com/pythonesque/fallthrough"
version = "0.0.1"
